title: <p align="center"> Souvik Misra </p>
logo: /assets/img/my_prof.jpg

description:
  <p align="center">
  <a href="docs/Souvik_Profile.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/souvik-misra-0a281929/">LinkedIn</a> |
  <a href="https://github.com/svkmsr6">GitHub</a>
  
  <br> 
  <ul>
  <li>I'm working on Data Science, Machine learning & NLP related problems.</li>
  <li>Worked with TCS in CPG at Apple PS for 2.3 years.</li>
  <li>Worked with Dassault Systemes in Supply Chain for 2.2 years.</li>
  <li>Worked with Bridgei2i Analytics Solution in Finance and insurance for 1.75 years.</li>
  <li>Working in Maersk GSC in Logistics Domain for 3+ years.</li>
  </ul>
  <br>
  </p>



theme: jekyll-theme-minimal
